const data = [
  {
    id: "11",
    title: "Money Heist",
    URL: "https://images.thequint.com/thequint%2F2021-09%2Fb9aab177-f368-4185-91b4-b37f15c2b7ee%2Fmoneyheist.png?auto=format%2Ccompress&fmt=webp",
    releaseDate: "02-May-2017",
    timeDuration: "5 Seasons",
    gener: "Crime Suspenseful Exciting",
    age: "16+",
  },
  {
    id: "12",
    title: "Lucifer",
    URL: "https://releasedate.news/wp-content/uploads/2021/05/Lucifer-Season-6-What-Netflix-Release-Date-A-planned-sequel.jpg",
    releaseDate: "25-jan-2016",
    timeDuration: "6 Seasons",
    gener: "Detective fantasy Comedy-drama",
    age: "18+",
  },
  {
    id: "13",
    title: "Kate",
    URL: "https://ntvb.tmsimg.com/assets/p20115224_v_h8_aa.jpg?w=960&h=540",
    releaseDate: "10-sep-2021",
    timeDuration: "1h 46m",
    gener: "Thriller Adventure",
    age: "18+",
  },
  {
    id: "14",
    title: "The Witcher",
    URL: "https://resizing.flixster.com/48Fl1jGadkTYasxqdFtg0CuGjhw=/1100x618/v2/https://resizing.flixster.com/-XZAfHZM39UwaGJIFWKAE8fS0ak=/v3/t/assets/p17580186_b_h8_ak.jpg",
    releaseDate: "20-dec-2019",
    timeDuration: "2 seasons",
    gener: "Fantasy ",
    age: "18+",
  },
  {
    id: "15",
    title: "6 Underground",
    URL: "https://geekireland.com/wp-content/uploads/2019/12/6-underground.jpg",
    releaseDate: "10-dec-2019",
    timeDuration: "2h 8m",
    gener: "Action/Thriller ",
    age: "18+",
  },
  {
    id: "16",
    title: "Peaky Blinders",
    URL: "https://e0.pxfuel.com/wallpapers/962/608/desktop-wallpaper-peaky-blinders-peaky-blinders-poster-peaky-blinders-peaky-blinders.jpg",
    releaseDate: "12-sep-2013",
    timeDuration: "5 seasons",
    gener: "Drama Violent",
    age: "18+",
  },
  {
    id: "17",
    title: "Stranger Things",
    URL: "https://imgix.bustle.com/inverse/98/13/35/e4/575e/4b20/afee/9ab390c35770/stranger-things-3-monster.jpeg?w=1200&h=630&fit=crop&crop=faces&fm=jpg",
    releaseDate: "15-july-2016",
    timeDuration: "3 seasons",
    gener: "Sci-fi Scary Exciting",
    age: "16+",
  },
  {
    id: "",
    title: "The Old Guard",
    URL: "https://w0.peakpx.com/wallpaper/470/16/HD-wallpaper-charlize-theron-movie-chiwetel-ejiofor-matthias-schoenaerts-marwan-kenzari-andromache-of-scythia-the-old-guard-booker-the-old-guard-copley-the-old-guard-kiki-layne-luca-marinelli-nicky.jpg",
    releaseDate: "10-july-2020",
    timeDuration: "2h 5m",
    gener: "Action Fantasy",
    age: "18+",
  },
];

export default data;
